# Dependencies
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            SMVS
tagline:          'Shading-aware Multi-view Stereo'
description:      'This is a changelog for the GitHub project'
baseurl:          "/smvs"
version:          0.1

author:
  name:           'Fabian Langguth'

paginate:         5

# Custom vars
gems: [jekyll-paginate, jekyll-gist]

github:
  repo:           https://github.com/flanggut/smvs
